### ISSUE TITLE
Linear Algebra Library - which implementation 

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#12]
I ran across this trying to bring my 3C seismogram into the mspass framework.   That set of code makes extensive of the blas.  That was solved with using openblas and replacing all calls to things like ddot to cblas_ddot.   I could have probably also used gsl_ddot, although I didn't verify the API was identical.

I ran into issues when I tried to compile this and got errors because one of the methods uses the dgetrf and dgetri  algorithms to invert a transformation matrix.   That is needed, for example, to restore rotated data back to standard coordinates - i.e. undo any transformations or fix orientation problems.   What happened was I discovered there are a lot of different implementations of a C interface to LAPACK, which is where these routines come from.   openblas has one form, but it does not appear to be unique.  It seems modeled after netlib and an intel library.    

I have two issues for discussion:
1.   Is openblas the right source for blas and lapack routines?   blas seems more sensible since it is in the name of the package, but the lapack seems like an add on.  The documentation hardly mentions lapack, although perhaps that is the definition of blas level 3?   
2.   I can't figure out why cmake does not seem to be installing openblas on this mac laptop.  I think it is finding cblas.h in some xcode framework and using that and that is fooling cmake somehow.  I suspect it works correctly on the uits linux computers, but that is an untested guess.  What is stumping me right now is  how to proceed to get cmake to actually install openblas on this mac.   I can push everything to the uits system but that may just be sweeping the problem under the rug and asking for more problems later.   Ideas?

**Comment by wangyinz** [comment]
That's indeed a problem I have been worrying about for a while. The issue with blas and lapack is that a lot of different libraries have implemented them with a little bit of variation. I have seen projects that uses a lot of ifdef statements to implement all possible variations. The specific issue you found on mac is the same case. Mac comes with this vecLib that contains its own implementation of blas and lapack. Right now our cmake script is not really written to adapt to all the variants including the vecLib. I think the best way to do this is look at other libraries and see if there is a clean way to adapt to all these. I do not have a good idea right now neither.

**Comment by wangyinz** [comment]
Maybe using cblas is not a great idea. Alternatively, we might just link to the library this way: http://www.phy.olemiss.edu/~kbeach/guide/2013/01/01/lapack/

**Comment by wangyinz** [comment]
To figure out the behavior of the compiler on fortran-C interface, we might use this cmake module:
https://cmake.org/cmake/help/latest/module/FortranCInterface.html

**Comment by wangyinz** [comment]
Or, we could use the more standard [LAPACKE](http://www.netlib.org/lapack/lapacke.html) interface, but we will then need to find a FindLAPACKE module to identify that library, just like how I did in FindCBLAS. I actually prefer the Fortran-C interface solution after reading all different opinions online. What do you think?

**Comment by pavlis** [comment]
You are clearly way ahead of me on this.   My thoughts are that since we are using cmake if there is a clean, standard cmake way to do this with the FORTRAN interface we maybe should just use that.  The goal should be to make it as automatic as possible to get the optimized code, which is usually the fortran code.

The flip side of that is making making sure fortran and C play well together isn't always simple, although it is a lot easier than it once was.   Just like children with time they learned to get along. Given our community I don't think it will be a big issue if mspass requires a fortran compiler for support.  The brtt people, particularly Dan Quinlan who wrote most of the low level functionality of antelope, were always a bit snooty about fortran, but I think we need to be agnostic on this issue. A lot of people in seismology still use FORTRAN (especially newer versions) and there is a huge amount of legacy fortran code.   

The other bad thing about the fortran interface is that the pure form demands all arguments be pointers.   That creates some really awkward constructs like this one I just made up as an example from memory in the deep past before the days of cblas:

int ndata=d.ns;
int one(1);
double sc=some computed value
// Assume d is a previously set array of length ndata
dscal_(&ndata,&sc,d,&one);

So, some form of C wrappers helps clean up the API, but if we can do that and still maintain an automatic link to optimized algorithms it would be best.  You tell me how to proceed and I'll adapt the code to use what you choose.

**Comment by pavlis** [comment]
Note - that little code snippet I just entered has a stupid mistake.  d.ns is not consistent with using d as an array name.  The point of that was that for the FORTRAN interface you need silly constructs like &one.

**Comment by wangyinz** [comment]
Totally agree. I have implemented a version with fortran C interface. Turns out it is a little more tricky than I thought, and I would like to stress that there is no "standard cmake way" as far as I can tell. Anyway, I believe the code itself appears a lot cleaner in this version. The essence here is  this section 
```
#include "FC.h"

extern "C" double ddot (
  const int& n, 
  const double* x, const int& incx,
  const double* y, const int& incy);
```
in [dmatrix.cc](https://github.com/wangyinz/mspass/blob/master/cxx/src/lib/utility/dmatrix.cc), the `${PROJECT_SOURCE_DIR}/include` line in the corresponding [CMakeLists.txt](https://github.com/wangyinz/mspass/blob/75ab7e8b5419275ddee28afe52efdb60cc0263df/cxx/src/lib/utility/CMakeLists.txt#L4), and the `list (APPEND FORTRAN_FUNCTIONS ddot)` in the master [CMakeLists.txt](https://github.com/wangyinz/mspass/blob/75ab7e8b5419275ddee28afe52efdb60cc0263df/cxx/CMakeLists.txt#L37).  Basically, you will need to correspondingly add other blas/lapack functions when needed following this example with `ddot`.

**Comment by wangyinz** [comment]
Well, since this version does not have lapack function in it, I will need to write and test other parts to make sure cmake finds the lapack library in configure step. Right now, I am 90% positive that the blas is implemented flawlessly.

**Comment by pavlis** [comment]
We might want to put all these in one standard include file in mspass.  What binaries will these be linked against this way?   

What does the FC.h include do?   Is that what is defining C bindings?

**Comment by wangyinz** [comment]
Yes, commonly people will have a dedicated header that defines all the blas and lapack functions. I do it this way mostly because we are only using this one function right now, and likely won't have more than a couple in the end. Definitely please feel free to create a dedicated header under `include/internal/`.

Right now, I am using the FindBLAS module that comes with cmake, which will locate a libblas library file and put it in `$BLAS_LIBRARIES`. It supports a long list of venders and should find something most of the time. I tweaked a little bit that if none is found, it will build openblas, and point that variable to it. I tested on Mac, in Docker, and on Stampede2, and it works fine under all different environments.

The `FC.h` is generated by cmake from [this line](https://github.com/wangyinz/mspass/blob/75ab7e8b5419275ddee28afe52efdb60cc0263df/cxx/CMakeLists.txt#L38). It automatically detects the mangling convention the C/Fortran compiler uses, and this header file contains the necessary macros to convert the function names given in that `FORTRAN_FUNCTIONS` list. Because this is taken care of, we can just call the blas function directly [here](https://github.com/wangyinz/mspass/blob/75ab7e8b5419275ddee28afe52efdb60cc0263df/cxx/src/lib/utility/dmatrix.cc#L153).

**Comment by pavlis** [comment]
Ok, I'm figuring some of this out now and see this should be a good solution.   
I'm stumped on somethign though.   I followed your dmatrix example in a new file Seismogram.cc.  Here specifically is what I inserted:
#include "FC.h"
/* This is a temporary hack fix for mac laptop.   Had fink install
   openblas.  This is the fink default location for include files. */
//#include "/sw/include/lapacke.h"
/* These should com from lapacke.h but there are some collisions with 
 * boost that create compile errors. Hack fix until we resolve the 
 * issue of how we will standardize lapack version.*/
#define LAPACK_ROW_MAJOR               101
#define LAPACK_COL_MAJOR               102
#include "seismic/Seismogram.h"
#include "mspass/MsPASSError.h"
#include "mspass/SphericalCoordinate.h"
/* For now we put these prototypes here - should be made an include
   file when we stablize how blas and lapack should be handled. */
extern "C" {
double ddot(int,double *,int,double*,int);
double dscal(int,double,double*,int);
double daxpy(int,double,double*,int,double*,int);
double dcopy(int,double*,int,double*,int);
int LAPACKE_dgetrf(int,int,int,double*,int,int*);
int LAPACKE_dgetri(int,int,double*,int,int *);
};

When cmake tries to compile this file I get this:
[ 48%] Building CXX object src/lib/seismic/CMakeFiles/seismic.dir/Seismogram.cc.o
/Users/pavlis/src/mspass/cxx/src/lib/seismic/Seismogram.cc:4:10: fatal error: 
      'FC.h' file not found
#include "FC.h"
         ^~~~~~
1 error generated.

I dug a bit in the files CMake creates and I think I see why.  For the mspass library a file deep in the build directories called flags.make has this:
CXX_INCLUDES = -I/opt/boost/include -I/Users/pavlis/src/mspass/cxx/include -I/Users/pavlis/src/mspass/cxx/build/include

The same file for a new "seismic" library has this in flags.make
CXX_INCLUDES = -I/opt/boost/include -I/Users/pavlis/src/mspass/cxx/include

the -/build/include where FC.h is found is missing.  I managed to get the seismic library built correctly before this recent change.  Any ideas?

**Comment by wangyinz** [comment]
My bad. I got that mixed up. You need to add `${PROJECT_BINARY_DIR}/include` to the CMakeFileList.txt in addition to the `${PROJECT_SOURCE_DIR}/include`.

**Comment by pavlis** [comment]
Ahh - that did it.   I should have noticed that difference.   It was late for me when I was working on that.   Just checked in a massive revision with core seismic objects.   The test_tcs program to test the 3c seismogram object runs but is grossly incomplete.   I'm going to start a new discussion thread for some api issues we need to iron out about next steps.
