### ISSUE TITLE
Confirm the test results of cxx

### ISSUE THREAD

**Issue by wangyinz** [wangyinz/mspass#14]
Please confirm the all the tests are giving the expected results after my recent re-organization. Also, I would like to integrate them into the ctest workflow, which right now only as the `test_dmatrix` in it.

**Comment by pavlis** [comment]
I fixed some problems in Seismogram and revised the test_tcs program files.   I think I did the cmake configuration changes to implement all the tests, but I am left with a dumb question:  how do I run and check the output of the automated tests?  I remember you showing me yesterday, but I didn't retain it.

**Comment by wangyinz** [comment]
It's `make test`

**Comment by wangyinz** [comment]
I don't see the changes. Are they in a different branch?

**Comment by pavlis** [comment]
Committed the changes to master only a couple of hours ago.   Had some bug fixes before I wanted to put it onto the master. 

I'm going to leave most of these tests in two forms.  The automated part is handled with the exit code.  The test will fail if the code detects an inconsistency or throws an exception.   A tougher problem is if the test runs to completion but has the wrong output.   To do that I'm setting up all the tests with an output file of the expected output.   I would like to treat these as a secondary level of testing to validate code.  The best example is test_tcs that has some transformation tests for which the only way I could validate the algorithm was to run it against a complimentary matlab script.  A full validation would be really hard for a variety of reasons.   Any ideas you would have on how we should do this as the package develops would be helpful.   Otherwise, I think we can close this thread.
