### ISSUE TITLE
make install anomaly

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#160]
I think this belongs in issues because it doesn't deserve a discussion.   I discovered a problem in the cmake setup when one issues:
```
env MSPASS_HOME=my_mspass_home
cmake ..
make install
```
The problem is that the install setup installs include files found in cxx/include/mspass BUT it does not copy cxx/include/misc/blash.h.  That does not matter to running setup.py or internal development of mspass alone, but causes a confusing incompatibility when I try to compile external C code.   Perhaps other packages should handle blas.h themselves, but it is a confusing gap because one would expect cxx/include to all be copied to the install include directory.

**Comment by wangyinz** [comment]
hmmm... but I checked and do think it is the right behavior. The files under `cxx/include/misc` are really external code that MsPASS depends on but does not own. That's why they were put in a different directory and set with a different namespace. They are no different than the boost or gsl library, which are not gonna be installed by mspass neither. When users link mspass libraries in another project, those headers under misc are no longer dependents to mspass libraries (because none of those headers were included by a mspass header file). I wonder how the misc headers came up in your case. Are they referenced by a header that I missed? If so, we do need to fix that header and remove such a dependency.

**Comment by pavlis** [comment]
I can see that viewpoint.  It came up because while hacking to adapt pwmig to mspass I quickly remembered that pwmig made an extensive use of an open source library in antelope contrib called "perf" (performance).   The contents of that library are similar but not identical to openblas.   I believe you constructed misc/blas.h and it contained all the prototypes I needed without all the baggage in openblas.   

I think the solution for my conversion is to  simply copy misc/blas.h into pwmig and use openblas the same way as mspass.   the file is tiny and it is probably better to maintain the copy than to maintain a special link to mspass.

**Comment by wangyinz** [comment]
aha, I see. In this case, copying `misc/blas.h` to pwmig is the best solution. That's also how it worked for mspass - we should consider that the file was copied from somewhere else.
