### ISSUE TITLE
processing functions and spark

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#21]
As I told by email I have the basic wrappers for the C++ code finished.   They remain to be fully tested.  In my current situation with grandkids I can't spend time doing that, but I have been thinking about how algorithms should be set up to interact correctly with SPARK.   A quick search got me to this extremely useful page I'm sure you are well aware of by I want to preserve here for later reference:  https://www.tutorialspoint.com/apache_spark/apache_spark_core_programming.htm

Clearly things like filter, map, collect, and reduce are key features.  Not yet clear to me when the other methods mentioned there are appropriate, but presume that will become apparent as I learn this.   

I was thinking of adapting a C++ program I have to compute a 3C agc as a lightweight first algorithm to try.   I can do the coding for that and make a wrapper in an hour or so, but something I don't understand about spark at this point are a couple of fundamental issues:
1. I believe the model is that inputs are always treated as immutable.   Is that true?
2. Is there a hidden copy overhead in map?   i.e. especially in a distributed system it would seem required that some or all data get copied before processed.   Is that true?   Do I best view that as not my problem?
3.  Since python is agnostic about type I presume input and outputs can be whatever and the interpreter handles the types internally.  Is that right?
4.  What happens if the function passed to map sometimes throws an exception and fails?   Maybe that is in a section I haven't gotten to yet.

Enough for now.   Actually, pretty clearly the first thing I need to do when I have a block of time to do so is run your example python script under spark.   That likely will teach me more.  It would be helpful, however, if you could extend that example by calling a custom python script instead of the inline function your example uses.   I assume the idea is to have a symbol defined in a module such as 
import mspasspy as msp
map(blah,blah, msp.agc,blah)

**Comment by pavlis** [comment]
Design issue:  Just went back to reading the page noted above and noted something I missed on the first quick pass:  pipe.   Not a first order thing to try, but suspect that might be a good way to handle chains of process filters.   I have the machinery in antelope contrib to push data through pipes using boost serialization.   Worth keeping in mind as it might make some processing chains more efficient.

**Comment by wangyinz** [comment]
I think we don't really have to explore all the features of Spark as I think it will mostly be used as a task scheduler for processing. Map and reduce should cover most of our use cases. 

To your questions:

> 1. I believe the model is that inputs are always treated as immutable. Is that true?
I think so. Each action or transformation should generate a new RDD. 

> 2. Is there a hidden copy overhead in map? i.e. especially in a distributed system it would seem required that some or all data get copied before processed. Is that true? Do I best view that as not my problem?
Yes, there is definitely overhead in distributing the original data set from one node too all the others. There will also be overheads in communication in a chain of processing steps. There could be some significant memory consumption from all these, and I think I've seen people complaining about this when using Spark. However, just as you said, this is not our problem, and Spark is designed to be able to do all these efficiently. In the case we figured it is not a good fit for our application, we might also consider something else. Because our user interface will be based on Python, it should be straightforward to switch to something Spark alike that are available out there.  

> 3. Since python is agnostic about type I presume input and outputs can be whatever and the interpreter handles the types internally. Is that right?
Yes, we got a lot of freedom here, and it could be dangerous, too.

> 4. What happens if the function passed to map sometimes throws an exception and fails? Maybe that is in a section I haven't gotten to yet.
I don't think Spark handles exceptions, but we should always implement exception handler within the functions for users anyway. Spark will terminate all parallel tasks when encountering error in any concurrently running tasks. We can handle the exception based on the severity to decide whether terminate the parallel tasks or just skip something silently.

**Comment by pavlis** [comment]
Thanks for the education.  I realize now we visited the exception question in a less specific way earlier.  It is, in fact, why I created the ErrorLogger class to allow error handler to to not abort an entire map/reduce operation but only post an "Invalid" flag on a log entry.

**Comment by wangyinz** [comment]
discussion in #11
